=== Xadouuu7/hospital/python/Bloque Conexión Login/patologies.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="table">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="row" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Patologia" type="xs:string" minOccurs="1" maxOccurs="1"></xs:element>
                            <xs:element name="Total" type="xs:integer" minOccurs="1" maxOccurs="1"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Xadouuu7/hospital/python/Bloque Conexión Login/patologies.xml
<table xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="patologies.xsd">
    

<row>
  <Patologia>vaginofobia</Patologia>
  <Total>179</Total>
</row>

<row>
  <Patologia>fimosis</Patologia>
  <Total>165</Total>
</row>

<row>
  <Patologia>tetafobia</Patologia>
  <Total>56</Total>
</row>

</table>
